-- FOILRACE — schéma Supabase initial

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  pseudo text not null check (char_length(pseudo) between 2 and 24),
  avatar_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_pseudo_unique
  on public.profiles (lower(pseudo));

create table if not exists public.runs (
  id bigint generated by default as identity primary key,
  rider_id uuid not null references public.profiles(id) on delete cascade,
  elapsed_centiseconds integer not null check (elapsed_centiseconds > 0),
  source text not null default 'foilrace-timer',
  validated boolean not null default true,
  recorded_at timestamptz not null default now()
);

create index if not exists runs_rider_time_idx
  on public.runs (rider_id, elapsed_centiseconds);

alter table public.profiles enable row level security;
alter table public.runs enable row level security;

create policy "Classement public : profils lisibles"
  on public.profiles for select using (true);
create policy "Le rider modifie son profil"
  on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "Classement public : runs validés lisibles"
  on public.runs for select using (validated = true);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, pseudo)
  values (new.id, coalesce(nullif(trim(new.raw_user_meta_data ->> 'pseudo'), ''), 'Rider-' || left(new.id::text, 6)));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace view public.leaderboard
with (security_invoker = true)
as
select
  p.id as rider_id,
  p.pseudo,
  p.avatar_path,
  count(r.id)::integer as run_count,
  min(r.elapsed_centiseconds)::integer as best_time_cs,
  max(r.recorded_at) as last_run_at
from public.profiles p
join public.runs r on r.rider_id = p.id
where r.validated = true
group by p.id, p.pseudo, p.avatar_path;

grant select on public.leaderboard to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Photos publiques en lecture"
  on storage.objects for select using (bucket_id = 'avatars');
create policy "Le rider ajoute sa photo"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "Le rider remplace sa photo"
  on storage.objects for update to authenticated
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
