-- FOILRACE — schéma Supabase
-- Auth e-mail/mot de passe, classement public et avatars contrôlés par RLS.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  pseudo text not null check (char_length(pseudo) between 2 and 24),
  avatar_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_pseudo_unique
  on public.profiles (lower(pseudo));

create table if not exists public.runs (
  id bigint generated by default as identity primary key,
  rider_id uuid not null references public.profiles(id) on delete cascade,
  elapsed_centiseconds integer not null check (elapsed_centiseconds > 0),
  season integer not null default extract(year from current_date)::integer check (season between 2026 and 2100),
  source text not null default 'foilrace-timer',
  validated boolean not null default true,
  recorded_at timestamptz not null default now()
);

create index if not exists runs_rider_time_idx
  on public.runs (rider_id, elapsed_centiseconds);

alter table public.profiles enable row level security;
alter table public.runs enable row level security;

drop policy if exists "Classement public : profils lisibles" on public.profiles;
create policy "Classement public : profils lisibles"
  on public.profiles for select
  to anon, authenticated
  using (true);

drop policy if exists "Le rider modifie son profil" on public.profiles;
create policy "Le rider modifie son profil"
  on public.profiles for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists "Classement public : runs validés lisibles" on public.runs;
create policy "Classement public : runs validés lisibles"
  on public.runs for select
  to anon, authenticated
  using (validated = true);

drop policy if exists "Le rider enregistre son chrono" on public.runs;
create policy "Le rider enregistre son chrono"
  on public.runs for insert
  to authenticated
  with check (
    (select auth.uid()) = rider_id
    and source = 'manual-web'
    and validated = true
  );

grant usage on schema public to anon, authenticated;
grant select on public.profiles, public.runs to anon, authenticated;
grant insert (rider_id, elapsed_centiseconds, source, validated, season) on public.runs to authenticated;
grant usage, select on sequence public.runs_id_seq to authenticated;
grant update (avatar_path, updated_at) on public.profiles to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, pseudo)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'pseudo'), ''), 'Rider-' || left(new.id::text, 6))
  );
  return new;
end;
$$;

-- La fonction privilégiée est réservée au trigger, jamais aux clients web.
revoke all on function public.handle_new_user() from public, anon, authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace view public.leaderboard
with (security_invoker = true)
as
select
  p.id as rider_id,
  p.pseudo,
  p.avatar_path,
  r.season,
  count(r.id)::integer as run_count,
  min(r.elapsed_centiseconds)::integer as best_time_cs,
  max(r.recorded_at) as last_run_at
from public.profiles p
join public.runs r on r.rider_id = p.id
where r.validated = true
group by p.id, p.pseudo, p.avatar_path, r.season;

grant select on public.leaderboard to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Photos publiques en lecture" on storage.objects;
create policy "Photos publiques en lecture"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'avatars');

drop policy if exists "Le rider ajoute sa photo" on storage.objects;
create policy "Le rider ajoute sa photo"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "Le rider remplace sa photo" on storage.objects;
create policy "Le rider remplace sa photo"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'avatars'
    and owner_id = (select auth.uid())::text
    and (storage.foldername(name))[1] = (select auth.uid())::text
  )
  with check (
    bucket_id = 'avatars'
    and owner_id = (select auth.uid())::text
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "Le rider supprime sa photo" on storage.objects;
create policy "Le rider supprime sa photo"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'avatars'
    and owner_id = (select auth.uid())::text
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
